### PR TITLE
[MPOM-348] Drop configuration for not used Maven Changes Plugin

### PR DESCRIPTION
**Pull request by slachiewicz**

### CODE REVIEW

**Comment by olamy** [comment]
after this change, I wonder if `Create an announcement.` section from [here](https://maven.apache.org/developers/release/maven-project-release-procedure.html) section will still work? 
@hboutemy ?

**Comment by michael-o** [comment]
> after this change, I wonder if `Create an announcement.` section from [here](https://maven.apache.org/developers/release/maven-project-release-procedure.html) section will still work? @hboutemy ?

Likely not. Personally, I have never used the Maven Changes Plugin for this.

**Comment by olamy** [comment]
> > after this change, I wonder if `Create an announcement.` section from [here](https://maven.apache.org/developers/release/maven-project-release-procedure.html) section will still work? @hboutemy ?
> 
> Likely not. Personally, I have never used the Maven Changes Plugin for this.

me neither :) but as it's part of the documentation.

**Review by gnodet — APPROVED** [review]
If the plugin is not used, I'm fine with the removal, but the doc should definitely be updated so that the related section is removed.
I'm planning a MAVEN-38 release next week, should that be included ?

**Comment by olamy** [comment]
@slachiewicz as asked in a previous comment please update the release process documentation here https://maven.apache.org/developers/release/maven-project-release-procedure.html as `Create an announcement` with using `maven-changes-plugin` will certainly not work anymore with this change.

**Comment by olamy** [comment]
@slachiewicz ping please fix documentation!

**Comment by slachiewicz** [comment]
done https://github.com/apache/maven-site/commit/9bb731504e71eac15ead884fbe0a265930317ac8

**Comment by jira-importer** [comment]
Resolve #274

**Pull request merged**
