### PR TITLE
[MPOM-250] remove taglets

### PR DESCRIPTION
**Pull request by elharo**
@rfscholte

### CODE REVIEW

**Comment by rfscholte** [comment]
Let's combine this by adding the following to the maven-plugin-plugin for the [descriptor-goal](https://maven.apache.org/plugin-tools/maven-plugin-plugin/descriptor-mojo.html#extractors) to ensure only the [JavaAnnotationsMojoDescriptorExtractor](https://maven.apache.org/plugin-tools/maven-plugin-tools-annotations/xref/org/apache/maven/tools/plugin/extractor/annotations/JavaAnnotationsMojoDescriptorExtractor.html#L82) is being used (with this taglets are really not used anymore):

     <extractors>
       <extractor>java-annotations</extractor>
     </extractors>

**Comment by elharo** [comment]
done

**Comment by slachiewicz** [comment]
Good reason to migrate our Maven Core ITs also to annotations

**Comment by elharo** [comment]
Ping @rfscholte Is this good to merge?

**Pull request closed without merging**
