### PR TITLE
Upgrade plugin versions to migrate to Doxia 2

### PR DESCRIPTION
**Pull request by slachiewicz**
Collect plugin upgrades to migrate to Doxia 2 stack.
We could first try to move our Maven projects then later wider for full ASF.

### CODE REVIEW

**Review by michael-o — CHANGES_REQUESTED** [review]
There are few more updates already, can you fix?

**Comment by slachiewicz** [comment]
Okay, now all the properties from the parent with Doxia. We may have here a few more.

Are we done with plugin updates for Doxia 2? Do you think this kind of PR makes sense, or can we go with apache-parent update and release?

**Comment by slawekjaranowski** [comment]
As I know m-changes-p should be updated ... it is used eg by ASF commons project, commons projects also use own skin ... I think we should help they to migrate

**Comment by michael-o** [comment]
> Okay, now all the properties from the parent with Doxia. We may have here a few more.
> 
> Are we done with plugin updates for Doxia 2? Do you think this kind of PR makes sense, or can we go with apache-parent update and release?

See https://cwiki.apache.org/confluence/display/MAVEN/Towards+Doxia+2.0.0+Stack#TowardsDoxia2.0.0Stack-Progress

I would keep it for Maven Parent only before we broaden the scope.

**Comment by michael-o** [comment]
> As I know m-changes-p should be updated ... it is used eg by ASF commons project, commons projects also use own skin ... I think we should help they to migrate

* Maven Changes Plugin: https://lists.apache.org/thread/pgj1gd75hx1dhq9spnl3c70xxt07corx I have a private talk with @garydgregory and @ottlinger how to move forward here. I love the plugin, but too much effort with the current state. There is a workaround with `post-site` phase and Ant regex replacement to make it work.
* Commons Skin: This one was doomed for a long time. It is a fork from an old Fluido skin version which has never merged back our changes. I recommended @garygregory either rebase on top of Fluido 2.0.0, drop it, or work our the diffs and see whether we could add into fluido.

**Comment by ottlinger** [comment]
Creadur RAT uses Maven changes plugin to generate the release mail and a webpage report of all the stuff that happened within a release including links to Jira, so I'm happy for a way forward here .... other reports are not working as can be see by comparing:
* https://creadur.apache.org/rat017/ (current v0.17 old site) to
* https://creadur.apache.org/RAT-397/ (work in progress migration to the new site/doxia stack).

Multiple reports have broken layout, such as:
* https://creadur.apache.org/RAT-397/changes-report.html
* https://creadur.apache.org/RAT-397/jira-report.html

**Comment by michael-o** [comment]
> Creadur RAT uses Maven changes plugin to generate the release mail and a webpage report of all the stuff that happened within a release including links to Jira, so I'm happy for a way forward here .... other reports are not working as can be see by comparing:
> 
> * https://creadur.apache.org/rat017/ (current v0.17 old site) to
> * https://creadur.apache.org/RAT-397/ (work in progress migration to the new site/doxia stack).
> 
> Multiple reports have broken layout, such as:
> 
> * https://creadur.apache.org/RAT-397/changes-report.html
> * https://creadur.apache.org/RAT-397/jira-report.html

Read my workaround above.

**Comment by slachiewicz** [comment]
> > Okay, now all the properties from the parent with Doxia. We may have here a few more.
> > Are we done with plugin updates for Doxia 2? Do you think this kind of PR makes sense, or can we go with apache-parent update and release?
> 
> See https://cwiki.apache.org/confluence/display/MAVEN/Towards+Doxia+2.0.0+Stack#TowardsDoxia2.0.0Stack-Progress
> 
> I would keep it for Maven Parent only before we broaden the scope.


> 
> Progress
> Necessary changes performed at our (reporting) plugins
> 
> Format: {repository}: {branch-for-doxia-1.x}; {branch-for-doxia-2.0.0}
> 
> maven-help-plugin: maven-help-plugin-3.4.x; master
> maven-project-info-reports-plugin: maven-project-info-reports-plugin-3.6.x; master
> maven-invoker-plugin: maven-invoker-plugin-3.7.x; mater
> maven-dependency-plugin: maven-dependency-plugin-3.7.x; master
> maven-plugin-tools: maven-plugin-tools-3.14.x; master
> maven-jxr: jxr-3.4.x; master
> maven-pmd-plugin: maven-pmd-plugin-3.24.x; master
> maven-javadoc-plugin: maven-javadoc-plugin-3.8.x; master
> maven-checkstyle-plugin: maven-checkstyle-plugin-3.4.x; master
> maven-surefire: surefire-3.4.x; master
> Note: other reporting plugin will not be upgraded.

**Comment by slawekjaranowski** [comment]
maven-help-plugin - doesn't has a reports, so do not depends on doxia

**Review by gnodet — APPROVED** [review]

**Review by michael-o — CHANGES_REQUESTED** [review]
Some of them already have newer versions,  I'd use them.

**Comment by slachiewicz** [comment]
It would be easier to copy properties from the original parent pom and then let Dependabot open PRs with the latest versions, so we will also have Release Notes oob.

**Pull request closed without merging**
