### PR TITLE
[MPOM-295] Remove checkstyle from Maven site reports

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Comment by hboutemy** [comment]
not sure that this report costs much time
instead of dropping the report, looking at how to make such reviews more efficient would be useful
I know that dropping the report and ignoring the issue is easier

**Comment by slawekjaranowski** [comment]
Check style is used during each build and all discovered violations break build.
I don't see valuable usage  for skipped rules report.

**Comment by hboutemy** [comment]
not answering my question
and not solving any issue but removing a chance to change a threshold defined on some accepted rules

**Comment by slawekjaranowski** [comment]
We heave many other important issues that work with accepted rules ...

**Comment by hboutemy** [comment]
if there is a serious issue with the report, I won't fight either
but if it's only a matter of taste without real issue associated, I prefer to have the report

**Comment by slawekjaranowski** [comment]
@olamy are working on such reports during build time on jenkins.

Having report here we have view on issues in release time, more of component is release not often so historical view is not usable for me.

We should look at commit time if we remove some of issues and more important not introduce new one with next commit,
so CI is more expected place.

**Comment by slachiewicz** [comment]
+1 not useful to show empty page in our site report

**Comment by hboutemy** [comment]
> show empty page in our site report

@slachiewicz what site do you call "our site"?

**Comment by slawekjaranowski** [comment]
https://maven.apache.org/plugins/maven-clean-plugin/checkstyle.html

**Review by olamy — APPROVED** [review]
Agree. It's already enforced by the build which fail if there is any violations.
so it's just printing an empty report.

**Comment by slachiewicz** [comment]
https://maven.apache.org/wagon/checkstyle-aggregate.html

**Review by hboutemy — CHANGES_REQUESTED** [review]
-1
adding a report to Jenkins for HEAD is probably very interesting in addition to the report in release to stay as a point in time
but don't remove one for the other: both are useful

**Comment by hboutemy** [comment]
taking a random example https://maven.apache.org/plugins/maven-site-plugin/checkstyle.html
is it empty?

**Comment by olamy** [comment]
So do we fix it? 
I'm convinced we do not need this reports as Jenkins can do it for master/main (i.e what you are working).
Definitely not convinced about any reason why we need to archive this for every single release..
especially when we do not fix what is reported.... 
if it;'s important it should fail the build.
it is just delaying and taking longer to generate a site which should be only a matter of documentation.
Maybe long time ago it was usefull when sonar or jenkins or etc... didn;t exist but now let's have this with the CI..
So you can read your build result and all the reports all together as it's more important to have this published for code changes.

**Comment by slawekjaranowski** [comment]
My opinion is the same as @olamy  ... we don't need store such information corresponding for release build time. 
Nowadays we have ci system for it.
And when checkstyle find violation build will be break so report contains not important information.

**Comment by hboutemy** [comment]
I was as clear as I could with my -1 = short answer to avoid long discussion that I thought would be avoided after the "I will not fight for it" early answer I got

there is nothing to "fix" because nothing is broken with these reports

but I agree that I would love to see the report on CI https://ci-maven.apache.org/job/Maven/job/maven-box/job/maven-clean-plugin/job/master/

**Comment by jira-importer** [comment]
Resolve #252

**Pull request closed without merging**
