### PR TITLE
[MPOM-346] publish SBOM on release

### PR DESCRIPTION
**Pull request by hboutemy**
see https://cwiki.apache.org/confluence/display/COMDEV/SBOM

with https://github.com/CycloneDX/cyclonedx-maven-plugin/pull/242 fixed in `cyclonedx-maven-plugin` 2.7.4, using `makeAggregateBom` can be used everywhere

### CODE REVIEW

**Comment by michael-o** [comment]
How would such a BOM look like?

**Comment by hboutemy** [comment]
see for example https://repo1.maven.org/maven2/commons-daemon/commons-daemon/1.3.3/commons-daemon-1.3.3-cyclonedx.json

**Comment by brianf** [comment]
I think this is a great step forward in leading the charge towards standardizing sboms.

**Comment by michael-o** [comment]
> see for example https://repo1.maven.org/maven2/commons-daemon/commons-daemon/1.3.3/commons-daemon-1.3.3-cyclonedx.json

Here, the VCS URL looks wrong. It qualifies  for the browser only.

**Review by michael-o — APPROVED** [review]

**Comment by hboutemy** [comment]
> Here, the VCS URL looks wrong.

I'm convinced that by using the plugin and having more eyes, we'll improve step by step the heuristics to extract data from POMs...

**Comment by jira-importer** [comment]
Resolve #273

**Pull request merged**
