### PR TITLE
Bump m-site-p to 4.0.0-M8

### PR DESCRIPTION
**Pull request by gnodet**
# Conflicts:
#	pom.xml

### CODE REVIEW

**Review by michael-o — CHANGES_REQUESTED** [review]
I don't recommend upgrading yet since the current reporting plugins aren't prepared publically. All necessary changes still reside in `doxia-2.0.0` branches.

**Comment by gnodet** [comment]
> I don't recommend upgrading yet since the current reporting plugins aren't prepared publically. All necessary changes still reside in `doxia-2.0.0` branches.

This upgrade has the benefit of not depending on maven-compat.   
So is that a "I don't recommend" because it has not be much tested, or a "I don't recommend" because it will certainly break site rendering ? ;-)  That's also kinda why I put it in maven-parent and not maven-apache-parent...

**Comment by michael-o** [comment]
> > I don't recommend upgrading yet since the current reporting plugins aren't prepared publically. All necessary changes still reside in `doxia-2.0.0` branches.
> 
> This upgrade has the benefit of not depending on maven-compat. So is that a "I don't recommend" because it has not be much tested, or a "I don't recommend" because it will certainly break site rendering ? ;-) That's also kinda why I put it in maven-parent and not maven-apache-parent...

I concur since the maven-compat is still there, there is an open JIRA issue regarding that.

Both can happen, broken rendering or runtime errors. I haven't explicitly tried.

**Comment by gnodet** [comment]
> > > I don't recommend upgrading yet since the current reporting plugins aren't prepared publically. All necessary changes still reside in `doxia-2.0.0` branches.
> > 
> > 
> > This upgrade has the benefit of not depending on maven-compat. So is that a "I don't recommend" because it has not be much tested, or a "I don't recommend" because it will certainly break site rendering ? ;-) That's also kinda why I put it in maven-parent and not maven-apache-parent...
> 
> I concur since the maven-compat is still there, there is an open JIRA issue regarding that.
> 
> Both can happen, broken rendering or runtime errors. I haven't explicitly tried.

Sorry to not be clear.  With my experiments on making maven-compat optional, I had to upgrade to that version to be able to build maven without maven-compat.  So the plugin does not use it anymore at runtime as it now uses the resolver to do the needed work directly.

**Comment by michael-o** [comment]
> > > > I don't recommend upgrading yet since the current reporting plugins aren't prepared publically. All necessary changes still reside in `doxia-2.0.0` branches.
> > > 
> > > 
> > > This upgrade has the benefit of not depending on maven-compat. So is that a "I don't recommend" because it has not be much tested, or a "I don't recommend" because it will certainly break site rendering ? ;-) That's also kinda why I put it in maven-parent and not maven-apache-parent...
> > 
> > 
> > I concur since the maven-compat is still there, there is an open JIRA issue regarding that.
> > Both can happen, broken rendering or runtime errors. I haven't explicitly tried.
> 
> Sorry to not be clear. With my experiments on making maven-compat optional, I had to upgrade to that version to be able to build maven without maven-compat. So the plugin does not use it anymore at runtime as it now uses the resolver to do the needed work directly.

compat is used to get the WagonManager for `site-deploy`. Totally unrelated to Resolver usecase.

**Comment by slachiewicz** [comment]
Yes, I saw it. Hard hit.

**Comment by hboutemy** [comment]
> Yes, I saw it. Hard hit.

testing and breaking is life. We just need to revert and take time to analyze and fix
and make sure that the local problem won't become a global problem when put in a widely used parent POM

**Comment by michael-o** [comment]
> > Yes, I saw it. Hard hit.
> 
> testing and breaking is life. We just need to revert and take time to analyze and fix and make sure that the local problem won't become a global problem when put in a widely used parent POM

I'd like to stress out that I have diffed the output of every single reporting plugin we have before and after and addressed rendering issues. This should happen here as well.

**Comment by slachiewicz** [comment]
what about adding a special profile to easier test with the new Doxia stack?
We can override some properties, plugins etc.

**Comment by michael-o** [comment]
> what about adding a special profile to easier test with the new Doxia stack? We can override some properties, plugins etc.

This does not really make sense until I have released all reporting plugins with Doxia 2.0.0 stack otherwise you have to live with snapshots.

**Pull request closed without merging**
