### PR TITLE
[MPOM-421] Bump sisu from 0.3.5 to 0.9.0.M2

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Review by cstamas — APPROVED** [review]

**Comment by slachiewicz** [comment]
While I'm ok to use the newer Sisu plugin, I'm not sure about the impact of updating Sisu as dependency.

**Comment by gnodet** [comment]
> While I'm ok to use the newer Sisu plugin, I'm not sure about the impact of updating Sisu as dependency.

Agreed, though maven 3.9.x and master have recently upgraded to that one.

**Comment by slachiewicz** [comment]
> > While I'm ok to use the newer Sisu plugin, I'm not sure about the impact of updating Sisu as dependency.
> 
> Agreed, though maven 3.9.x and master have recently upgraded to that one.

That means if the min API level for the plugin will be updated to 3.9.3(?) This new impl will be injected by Maven. In any earlier Maven - plugin will get the old version. Right?
We are not using too much of Sisu internals yet. In the release note I saw enhancement to define configuration. Soon we may get Path support as Parameter type in Sisu, this may lead to some confusion, hope our CI could catch it.

**Review by slachiewicz — APPROVED** [review]

**Comment by gnodet** [comment]
> > > While I'm ok to use the newer Sisu plugin, I'm not sure about the impact of updating Sisu as dependency.
> > 
> > 
> > Agreed, though maven 3.9.x and master have recently upgraded to that one.
> 
> That means if the min API level for the plugin will be updated to 3.9.3(?) This new impl will be injected by Maven. In any earlier Maven - plugin will get the old version. Right? We are not using too much of Sisu internals yet. In the release note I saw enhancement to define configuration. Soon we may get Path support as Parameter type in Sisu, this may lead to some confusion, hope our CI could catch it.

Maven actually controls which version of sisu.plexus is used, so I doubt the upgrade will have any effect for plugins or other components since whatever they depend on will be overridden by the version provided by maven.  My goal was really to target the plugin or APT processor.

**Pull request merged**
