### PR TITLE
[MPOM-297] Remove taglist from Maven site reports

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Comment by hboutemy** [comment]
we probably should better define our tags for the report to be more useful, it's probably under-used
not sure how much time it costs: it's say not much

**Comment by hboutemy** [comment]
isn't this useful https://maven.apache.org/plugins/maven-deploy-plugin/taglist.html ?
how much time does this report cost that it is found too costly?
(for CI or for release manager?)

**Comment by slawekjaranowski** [comment]
TODO, FIXME and other ... can be reported by IDE if I need it
what release manager can do with such reports ... 
example of deprecated item is reported in Mojo documentations, and there is very useful.

**Comment by michael-o** [comment]
this report is really cheap. We should focus on reports which are long running or failure-prone.

**Comment by slawekjaranowski** [comment]
ok, I will not fight for it

**Review by slachiewicz — APPROVED** [review]

**Comment by Tibor17** [comment]
Not the release mgt can do something about this report at the release time. The important is what happens after the release, in the next dev iteration...

**Review by hboutemy — CHANGES_REQUESTED** [review]
-1
adding a report to Jenkins for HEAD is probably very interesting in addition to the report in release to stay as a point in time
but don't remove one for the other: both are useful

**Comment by jira-importer** [comment]
Resolve #253

**Pull request closed without merging**
