### PR TITLE
[MPOM-294] Remove surefire from Maven site reports

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Comment by michael-o** [comment]
@hboutemy

**Comment by hboutemy** [comment]
what is the problem with this report?

**Comment by slawekjaranowski** [comment]
The same information we have on CI
https://ci-maven.apache.org/job/Maven/job/maven-box/job/maven-deploy-plugin/job/master/lastCompletedBuild/testReport/org.apache.maven.plugins.deploy/

The biggest problem for this report is that test phase is triggered during site build ... and can take a long time.

We was start to validate site build on GH, Jenkins and want to improve it.

**Comment by hboutemy** [comment]
perhaps CI configuration should not be the same than release-time `-Preporting`

**Comment by michael-o** [comment]
I agreee with @hboutemy I don't see a huge reason to run `reporting` with CI.

**Comment by slawekjaranowski** [comment]
The most problematic and what should be tested is javadoc build, reports. But javadoc reports is in reporting profile.

**Comment by hboutemy** [comment]
why not just create a separate `ci` profile?

**Comment by slawekjaranowski** [comment]
we should run at least one build site (on os and jdk) with `reporting` profile to be sure that all plugins used in reporting profile still working.

**Review by olamy — APPROVED** [review]

**Comment by slachiewicz** [comment]
Knowing that we would have new pom soon - any decisions here?

**Comment by Tibor17** [comment]
hm, I do not understand his change.
The CI result is used to fail due to Socket time out. The same has happened in the latest surefire result vote. The build was red, we tried to restart the build for 3 days, and finally the build has got green at the end of the Vote.

Instead of removing the surefire report, we should adjust the process and the template should be changed and a new entry should be added along with Site link, SHA512, etc.

If one report is going to be removed, there should be some substitution but mandatory substitution done in prior.

This would improve the process while you prepare the release on your own, but this should not be all. This PR seems to be incomplete.

**Comment by slachiewicz** [comment]
https://maven.apache.org/wagon/surefire-report.html.

**Comment by Tibor17** [comment]
@slachiewicz
So, this zero report told me that we should ask the developer if the unit tests are really not interesting to write.

**Comment by slachiewicz** [comment]
https://maven.apache.org/surefire/surefire-report.html i would say that report is empty becouse running test was disabled while site publish runs

**Review by hboutemy — CHANGES_REQUESTED** [review]
-1

**Comment by jira-importer** [comment]
Resolve #250

**Pull request closed without merging**
