### PR TITLE
[MPOM-324] Drop Social Media Plug-ins from documentation

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Comment by michael-o** [comment]
So all subprojects will enherit from?

**Comment by slawekjaranowski** [comment]
> So all subprojects will inherit from?

Should ... but many times not - we need to check all projects 😄

**Comment by slawekjaranowski** [comment]
Like this https://github.com/apache/maven-site/pull/306

**Review by slachiewicz — APPROVED** [review]

**Review by michael-o — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
I checked some of last modified projects ... there is no override for it ... so looks ok.

**Comment by jira-importer** [comment]
Resolve #265

**Pull request merged**
