### PR TITLE
[MPOM-296] Remove pmd from Maven site reports

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Comment by hboutemy** [comment]
AFAIK, results from such report should be reviewed: the issue is not in the report but in how the output is not used

how much time does it cost (only at release time)?

**Comment by slawekjaranowski** [comment]
if we want pmd should be included in build, like checkstyle

**Comment by hboutemy** [comment]
I don't see why one would remove the usefulness of the other

**Comment by slawekjaranowski** [comment]
ok, I will not fight for it

**Comment by slawekjaranowski** [comment]
@olamy  are working on such reports during build time on jenkins.

Having report here we have view on issues in release time, more of component is release not often so historical view is not usable for me. 

We should look at commit time if we remove some of issues and more important  not introduce new one with next commit,
so CI is more expected place.

**Comment by slachiewicz** [comment]
https://maven.apache.org/jxr/pmd.html

**Review by hboutemy — CHANGES_REQUESTED** [review]
-1
adding a report to Jenkins for HEAD is probably very interesting in addition to the report in release to stay as a point in time
but don't remove one for the other: both are useful

**Comment by jira-importer** [comment]
Resolve #254

**Pull request closed without merging**
